sudo: required
services:
  - docker

before_install:
  - docker build -t ekram786/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ekram786/react-test npm test

after_success:
  - docker build -t ekram786/multi-client ./client
  - docker build -t ekram786/multi-nginx ./nginx
  - docker build -t ekram786/multi-server ./server
  - docker build -t ekram786/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ekram786/multi-client
  - docker push ekram786/multi-nginx
  - docker push ekram786/multi-server
  - docker push ekram786/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-235712339615
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"